### ISSUE TITLE
BMP280 device PCB design.

### ISSUE THREAD

**Issue by sakoPO** [microHAL/microhal#6]

**Comment by pjacalski** [comment]
Initial commit for i2c and SPI boards.
https://workspace.circuitmaker.com/Projects/Details/Pawel-Jacalski/UHALBMP280
https://workspace.circuitmaker.com/Projects/Details/Pawel-Jacalski/UHALBMP280SPI

**Comment by sakoPO** [comment]
In SPI design C3 have 10uF but partnumber shows 100nF, this causes issues while BOM generation. In BOM all capacitors are the same and have 100nF.
Please replace C3 to different part.
The same situation with resistors. BOM shows 0R resistors.

**Comment by pjacalski** [comment]
Deemed as moot.
